name: Docker Publish

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

env:
  IMAGE_NAME: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/ezppt

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-latest
          - arch: arm64
            runner: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image (${{ matrix.arch }})
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/${{ matrix.arch }}
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}-${{ matrix.arch }}
          cache-from: type=gha,scope=${{ matrix.arch }}
          cache-to: type=gha,mode=max,scope=${{ matrix.arch }}

      - name: Write image reference
        run: echo "${IMAGE_NAME}@${{ steps.build.outputs.digest }}" > refs-${{ matrix.arch }}.txt

      - name: Upload image digest
        uses: actions/upload-artifact@v4
        with:
          name: refs-${{ matrix.arch }}
          path: refs-${{ matrix.arch }}.txt

  manifest:
    name: Publish manifest
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download image digests
        uses: actions/download-artifact@v4
        with:
          pattern: refs-*
          merge-multiple: true
          path: .

      - name: Create and push multi-arch manifest
        run: |
          echo "Creating manifest for ${IMAGE_NAME}:latest"
          docker buildx imagetools create -t ${IMAGE_NAME}:latest $(cat refs-*.txt)
      - name: Inspect manifest
        run: docker buildx imagetools inspect ${IMAGE_NAME}:latest
